name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
        git config --global user.email "github-action-nagatani@users.noreply.github.com"
        git config --global user.name "gh-actions"
    - run: npm install
    - run: npm run build
    - run: npm run deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ github.token }}
